### ISSUE TITLE
デザインの確認、すり合わせ

### ISSUE THREAD

**Issue by ibuki2003** [afes-website/docs#1]
- ユーザーフレンドリーで現実的なものになるよう調整
- 持っているイメージが共通のものになるように話す

**Comment by su8ru** [comment]
![PC  トップページ](https://user-images.githubusercontent.com/33474143/72681493-94792a80-3b07-11ea-9e48-f88affe50613.png)
---
![PC  トップページ スクロール後](https://user-images.githubusercontent.com/33474143/72681499-97741b00-3b07-11ea-8732-e35f4f551583.png)
---
![mobile  トップページ](https://user-images.githubusercontent.com/33474143/72681500-9b07a200-3b07-11ea-9273-bc90416b997f.png)
---
![mobile  トップページ スクロール後](https://user-images.githubusercontent.com/33474143/72681503-9d69fc00-3b07-11ea-86fd-6cbe01ca598c.png)
