### ISSUE TITLE
トップページに使う文化祭の画像を工夫したい

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#12]
トップページに多分文化祭の風船の画像とか使うかな、とか思ってるんですけど、どうせなら
- 文化祭期間前→人の居ない中庭
- 文化祭期間中→円陣の中庭
- 文化祭期間後→風船！！
みたいにしたくないですかー？と思ったという話。

**Comment by su8ru** [comment]
疫病に 忍び泣きつつ そっと閉じ
