### ISSUE TITLE
ブログ執筆者の個人情報変更機能

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#14]
パスワードメールアドレス・名前の変更機能が必要な気がしている(僕の勝手な想定だと、最終的には60人くらい(各展責と多分各局長)に配布するから)

**Comment by ibuki2003** [comment]
名前変更→欲しい?
メールアドレス→結びつけ予定ありますか…?

**Comment by ibuki2003** [comment]
パスワード変更は実装済み、メールアドレスは使用予定がいまのところないので、closeします。reopenの可能性はあり。
