### ISSUE TITLE
生徒委員会からの要求

### ISSUE THREAD

**Issue by su8ru** [afes-website/docs#177]
呑むと .ed.jp にリンクを貼ってもらえるかも…？（職員会議案件ですが）

## 最低限

- **[削除] 近況 > 個人･寄稿**
  back 案件
  これは hidden でいいかなぁ
- **[削除] 文化祭資料ページ**
  front 案件
  router から削除でよさそう
  そもそもこれ教員側としてよく思ってないらしい（理由は容易に想像できる）

## リンクを貼るなら…？

- **[削除] 近況 全部**
  教員の目が届かないため
- **ウェブサイトについての詳細な説明の提出**
  21 の職員会議がデッドライン
  なので中間明けには資料を携えてちゃんと話す必要が
  - そもそもオンライン展示システムについては元々話す予定でしたが

追加情報についてもこの Issue で取り扱うことにします

**Comment by Takeno-hito** [comment]
がんむしした
