### ISSUE TITLE
[manage] 展示のstatusに含むtermの条件を決める

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#196]
## discuss

`exhibition/{id}/status/get` のcountで、返ってくるtermの一覧を定めたい。すくなくとも全部返す理由はない

定めるというのは例えば0人のtermについて返すかどうかとか。つまり下みたいな感じ

` { count: [ { term1: 1 } ], limit: 400, room_id: '101' }`
` { count: [ { term1: 1, term2: 0 } ], limit: 400, room_id: '101' }`

~~@su8ru﻿ 要望をかいてね~~
→ [ [入場時刻 ≦ 現在時刻 ≦ 退場時刻 を満たす] OR [人が居る] ] という条件でやります

----

## task

- [x] discuss
- [x] docs @Takeno-hito #196 
- [x] back @Takeno-hito

**Comment by su8ru** [comment]
フロントでどう出してるかなって思って Figma を見たらこんなかんじ。
少なくとも **現在有効な Term** は人の有無に関わらず返してほしいかなと

![image](https://user-images.githubusercontent.com/33474143/108598612-ed358980-73d1-11eb-98d6-9545cf6a8e67.png)

ただ、居残り組が消えても困るので、人がいる場合は現在有効でなくても含めてほしいなぁ

**Comment by Takeno-hito** [comment]
[入場時刻 =< 現在時刻 =< 退場時刻 を満たす] OR [人が居る] の条件づけでよさそう
