### ISSUE TITLE
Log取得のエンドポイントをまとめる

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#199]
現状だとExhibitionとGuestで散り散りになってる

- [ ] エンドポイントを1つにまとめる
- ~~Revision index の要領で Exhibition が叩いた時は自分のexhしか返ってこないようにする~~
- [ ] 検索条件をつけておく
  - [ ] reservationの権限を持ってる人だけreservation_id でも検索できるようにしておくとなお便利とみるのでやる

**Comment by su8ru** [comment]
これ、「メソッド」って「エンドポイント」を指していますか？

**Comment by Takeno-hito** [comment]
🙇‍♂️
