### ISSUE TITLE
予備のリストバンドを使用する方法を用意する

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#204]
おそらく新しいエンドポイントを用意するのが一番良い

**Comment by Takeno-hito** [comment]
お手軽不具合発生レシピ
1. 2人入れる予約を用意します
2. 1人checkinします
3. checkinした人が紛失して再発行します
4. 2人目checkinします
5. Errorが出ます

GuestにSpareフラグかなにかをもたせる必要がありそう

**Comment by su8ru** [comment]
spare として追加された guest は人数として計上されないし人数の制約も受けないということでいかがでしょうか

**Comment by ibuki2003** [comment]
展示内で紛失したときに困る件、予約人数全員退場したタイミングで残りのguestを強制退場させる方法を提案します

**Comment by su8ru** [comment]
## API 定義内に書けなかった仕様

### 1. 紛失されたリストバンドの強制退場

所属する予約のうち、紛失されたリストバンドを除く全てのリストバンド（紛失により発生したスペアを含む）が退場した場合、紛失されたリストバンドも退場処理される。
つまり予約人数が全員退場すると、紛失された最後の 1 つも退場処理される。

`is_force_revoked: true`

### 2. 人数カウント方法

[校内滞在者数] = [全 guests] - [全 spare] - [退場済]
