### ISSUE TITLE
develop • master 運用 / yarn version • npm publish の自動化

### ISSUE THREAD

**Issue by su8ru** [afes-website/docs#210]
develop への merge commit を hook して、こんな感じのことをする

```
yarn version --prerelease --preid alpha
npm publish --access public --tag alpha
```

ただ、develop -> master merge する日が来ない気もする

また、premajor / preminer / prepatch のことも考えると手動にすべきかもしれない

**Comment by Takeno-hito** [comment]
front/manage-appにおいて、develop ブランチでのdocsはalphaを使って、リリース時にreleaseされたdocsを使う方針でいいですか
