### ISSUE TITLE
/onsite/exhibition/{enter|exit} で展示が存在しない場合の挙動が未定義

### ISSUE THREAD

**Issue by su8ru** [afes-website/docs#212]
404 を返すか、`EXHIBITION_NOT_FOUND` が妥当では。

**Comment by Takeno-hito** [comment]
これ、ここまで来るとユーザー追加とか権限設定をできるapi、場所が必要じゃないかと感じ丸

**Comment by su8ru** [comment]
それは一つ一つ issue を立てていただいて……
