### ISSUE TITLE
⚠onsite関係のディレクトリ・権限構造の一新

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#222]
generalのgeneralしててgenerallllって感じがすごく微妙

**Comment by su8ru** [comment]
- api root に `/exhibitions` を追加
  全展示について、onsite・online 共通の id, name, icon (thumbnail から変更したい) 
  - それに伴い、既存のパス・モデルは `exhRoom` および `exhArticle` に変更
- `/onsite/general` のパス自体はそんなに悪くないと思ってるけど…
  どちらかというと権限名 `general` のほうが問題。`executive` とかにするべき。
  `/onsite/general/terms` とかは `/onsite/reservations` 内でいいんじゃないの…？とも思ったり…

**Comment by Takeno-hito** [comment]
やはりAPIを2つに分けたくなってきた

**Comment by Takeno-hito** [comment]
パス構造案 仮置

```
- auth (そのまま)
- image (そのまま)
- exhibition
  - enter
  - exit
  - status
- executive
  - exit
  - enter
- reservation
- term
- guest
- log
```

つまりonsiteとgeneralをほぼほぼ全部取っ払ってる感じ

これだとどうですか

**Comment by Takeno-hito** [comment]
`general`は`executive`にしましょう

**Comment by Takeno-hito** [comment]
```
- auth (そのまま)
- images (そのまま)
- exhibitions (元は exh/status)
  - :get 
  - {id}:get
- guests
  - check-in:post
  - {id}
    - :get 
    - enter:post
    - exit:post
    - check-out:post
- reservations (general/reservationから移動)
- terms:get
- log:get
```

権限名を general から executive に

でよい?
