### ISSUE TITLE
73afesと74afesのドキュメントを分割する

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#229]
## 73afes
- v2.3.0
- 使われていないpath (onsite/の全部) をすべて削除する
- online/{exhibition,draft} を {exhibition/draft} に移す
- exhibitionの名前は余裕があったら変えてもいい感じもするし、v2で作業できるような体制を残しておきたい
- tagつけるのかversionつけるのかはまだ決まってない感じがする

## 74afes
- v3.0.0-alpha.0
- onsiteの中身 を全部 ルートに移す
- online/*, article/*, revision/* を全部消す
- おそらくdevelopで運用を続ける

これに伴ってfront, backともに作業が必要になるはず

- [ ] front の v2.3.0 publish

**Comment by su8ru** [comment]
使われていない path を消すの、よくわからない
v3.0.0 のベースはどこ？

**Comment by Takeno-hito** [comment]
ベースはuserとonsite
使われてないpathは実際73Afesで使われてないのは消すべきじゃない?

**Comment by su8ru** [comment]
ベースブランチというかコミットというかタグというか、そういうあれ
2.2.x にあったものを 2.3.x で消すの、あまり理解ができないんだけど

**Comment by Takeno-hito** [comment]
3.0.0は今のdevelopそのまま続行でいいんじゃないの
それは、どちらかというと2.2.xでも本来は消されるべきだったような…?

**Comment by su8ru** [comment]
2.3.0-alpha.x で追加されてたものが 2.3.0 で綺麗サッパリ消えるの意味不明では…？

**Comment by Takeno-hito** [comment]
そこは2.2.12くらいから切るんじゃなかったの
そしてもしそこを気にするなら2.4.0じゃないのと

**Comment by su8ru** [comment]
2.2.12 から切るのか…
2.2.22 までリリースされてるのに、それらは 2.3.0 に含まれないとなるといよいよ意味不明では

**Comment by Takeno-hito** [comment]
え、2.3.0にonsite系は含まれてもいいと思ってるってこと？

**Comment by su8ru** [comment]
別にいいと思うけど

**Comment by su8ru** [comment]
yay!
