### ISSUE TITLE
Writerユーザでアクセスできるものはadminでアクセスできる必要はない

### ISSUE THREAD

**Issue by ibuki2003** [afes-website/docs#26]
多重OKにするとフロント/バックともに面倒な気がしたので。フロントはWriterを要求してるときはAdminを渡さなければいいだけ。

**Comment by Takeno-hito** [comment]
/blog/revisions/と、/blog/revisions/{id} をどうしようか悩んでる。/blog/revisions/{id}, /admin/revisions/{id} みたいな感じで分けててもいいなら分けた方が良いかなーと思ってる

**Comment by ibuki2003** [comment]
それの存在忘れてた /blog/revisions だけは両方で出来るようにしてもらうのがよいかも

**Comment by ibuki2003** [comment]
これはやめておくことにした
