### ISSUE TITLE
QR コードログイン対応

### ISSUE THREAD

**Issue by su8ru** [afes-website/docs#271]
`/auth/login/` に `encrypted_credentials` を渡す

1. JSON 形式で credentials を用意
   `{"id":"admin","pw":"ArNvc3LiLAPG"}`
2. base64 で難読化
3. QR コードにして各展示に配布
4. app で読んでデコード
5. back に投げて検証

**Comment by Takeno-hito** [comment]
暗号化する必要がなくなったので afes-website/cappuccino-app#127 単独
