### ISSUE TITLE
すべての 404 に error_code を定義する

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#276]
### 現状

```ts
   * @throws Error
   * 404: ID に該当する予約情報が存在しない
   *
   * @returns 入場可否の情報
   * valid: 入場可能であるかどうか
   * error_code: 入場可能である場合は null, そうでない場合は入場処理時に予約情報に関して返され得るコード; 対応表は以下
   * | error_code                    | Explanation                                |
   * | :---------------------------- | :----------------------------------------- |
   * | `RESERVATION_NOT_FOUND`       | 該当する予約情報が存在しない               |
   ```
- 存在しないなら 404 のエラーを返す
- 存在しないなら 200 が返ってきた上でその上で reservation_not_found が返ってくる

のどちらとも読み取る事ができる

それだけだったら良いんだけど、backエンドの大体の404エラーで docs には指定されてないのにも関わらず何故か `RESERVATION_NOT_FOUND` などを返させているパスが存在していて、混乱の元になっている

### 解決策?
- 全部の404エラーに error_code を返させるように統一する (要変更：docs)
- checkのコードの `RESERVATION_NOT_FOUND` の行だけを消して 404 の時に error_code なしに統一する (要変更：docs, back)

現状はこれのどっちにするかで決めかねている状態

**Comment by su8ru** [comment]
あったり無かったりするの面倒だし、ありに統一したい……

**Comment by ibuki2003** [comment]
RESTのお気持ちでいうと、パスが存在しないモノを指してるときは404を指すのが妥当そう

**Comment by su8ru** [comment]
明示的に定義されている 404 にのみ error_code を定義

明示的であるないを問わず 403・401 は定義しない
（境界が曖昧なのと、正しく実装されていれば目にすることのないエラー = 内部エラーとして処理して問題ないので）

**Comment by Takeno-hito** [comment]
これ、app側で作業する必要があることってありますか

**Comment by su8ru** [comment]
> @Takeno-hito これ、app側で作業する必要があることってありますか

status 404 で判定してたやつをエラーコードで見れるようになったり？
帰ったら確認します

**Comment by su8ru** [comment]
> > @Takeno-hito これ、app側で作業する必要があることってありますか
> 
> status 404 で判定してたやつをエラーコードで見れるようになったり？ 帰ったら確認します

確認しました
現在の develop のコードには 404 チェックをしているコードが無さそうです

いつかしれっと変更されたか、元から実装されていたものを使っていたかなので、Close して問題ないと思います
