### ISSUE TITLE
articleとrevisionでauthorを返すように

### ISSUE THREAD

**Issue by ibuki2003** [afes-website/docs#34]
というかauthorをidじゃなくてuser情報そのまま渡すべきなんだよね そのへんまとめて修正するべきそう

**Comment by su8ru** [comment]
完全に後出しで申し訳ないんだけど、revisionも

**Comment by ibuki2003** [comment]
~ひととおりできてるのでclose?~ →#39がmergedではなかったのね…

> 完全に後出しで申し訳ないんだけど、revisionも

完全に後出しなので別issueにして管理しなおしたほうがよいかもしれない

**Comment by Takeno-hito** [comment]
どうせなのでrevisionのも一緒に片付けます

**Comment by Takeno-hito** [comment]
### backの残りタスク
- [x] showでauthorオブジェクトを返すようにする → afes-website/back#37
- [ ] queryにauthor_idを含める → afes-website/back#40

**Comment by Takeno-hito** [comment]
ながらく放置されてましたが、frontが残ってます
