### ISSUE TITLE
revisionの提案をできるようにする

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#44]
変なrevisionがきたときに、LINE上でやりとりして提案してるんですけど、リンクを2つ送って「どっちがいいですか？」みたいな形にできるとすごい楽です

**Comment by ibuki2003** [comment]
admin級のユーザがrevisionを作成して記事作成者に見えるようにする みたいなのでどうかな
そうするとfrontの記事情報を読み込む、も最新revisionを参照できたほうがいいのだろうか

**Comment by Takeno-hito** [comment]
なるほど(今読んだ)
記事情報を読み込むには要らなくない…?あくまでsuggestでrevisionもう1個作ってるから。ただ最新revisionを参照という意味がよくわかってないから詳しく知りたいです

**Comment by su8ru** [comment]
記事情報を読み込むは、要るだろ（accept前はmdのコピーができないため）

**Comment by Takeno-hito** [comment]
僕が想定してるのは、特定のrevisionに対しての読み込みだけど、それとfrontの読み込むrevisionを最新のにする、ってなに

**Comment by ibuki2003** [comment]
frontの投稿時に表示される「記事内容を読み込む」の対象をarticleでなく最新revisionにする

**Comment by ibuki2003** [comment]
それともdropdownとか「このrevisionをもとにrevision新規作成」とかにしとく?

**Comment by Takeno-hito** [comment]
下の方がいいと思う

**Comment by Takeno-hito** [comment]
ならbackもdocsも変更なしってことで?

**Comment by ibuki2003** [comment]
Adminのwriterでrevisionを作成すればいいのか?
…authorがadminになっちゃうから特別な扱いが必要な気がする

**Comment by Takeno-hito** [comment]
あーそうね、、

**Comment by Takeno-hito** [comment]
Adminもブログ作成できるようにしようか、、?
author:を入れて、あと提案者、みたいなのが必要かしら

**Comment by ibuki2003** [comment]
writerは自分のしか見えないので、

- suggestionは完全別扱いにして宛先のカラムを追加してあげる
- statusにsuggestionというのを追加、Adminがsuggestionを作成するときは所有者を変更できる(Adminしかsuggestionできないけど)

とかがいいかな

**Comment by Takeno-hito** [comment]
#64 とかぶってたの忘れてたので一回こっちをclose
