### ISSUE TITLE
更新情報 記事の更新も表示

### ISSUE THREAD

**Issue by su8ru** [afes-website/docs#47]
トップページの更新情報で、記事の更新も表示できるようにする？

> 前話したように対象は記事ではなく更新なのでは？(APIの変更が必要になるのでtodoコメントつけて一旦放置するのが楽なんだろうけど)
> from @ibuki2003 
> afes-website/front#193 [comment](https://github.com/afes-website/front/pull/193#discussion_r400182520)

**Comment by ibuki2003** [comment]
これ、ブログ専用にする?(今後他のものが出てきたときもブログ記事で対応する?)
私は汎用のものが欲しいと思うんだけど、カテゴリとかが扱いにくくなりますね

**Comment by Takeno-hito** [comment]
allでfilterとかうまく使ったら最新の数件、みたいな取得いけないっけ、無理?

**Comment by ibuki2003** [comment]
APIの変更は必須かな

**Comment by ibuki2003** [comment]
変更を我々がブログ記事として投稿する、みたいな案が出たことがあって、そうするとブログだけ対応すればよくなるので楽

(今後ステージとか販売とかそういうのの更新情報が出てきたときはどうしたらいいんだ?そのとき考えるじゃよくない気がするんだよな)

**Comment by su8ru** [comment]
複数のエンドポイントを叩いて一緒にする（？）

**Comment by ibuki2003** [comment]
それもありかな デザインで苦悩するのは@su8ruだけなので(おい)

**Comment by su8ru** [comment]
archived つけたけど、結局これ表示される仕様だった気がしなくも……
