### ISSUE TITLE
review createの不備

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#49]
statusでnullが返ってくる。今のfrontで使ってないから急ぐ必要はないけど、bugはbug
https://github.com/laravel/framework/issues/21449
docsを変えるかbackを変えるかみたいな話をして終わったけど、どうしよう

**Comment by ibuki2003** [comment]
~docsで書いておいて何を言っているんだ…~
どうせ使われていないし使わないので、実装を変えるのは手間かなと思います 仕様書をいじればいい

**Comment by ibuki2003** [comment]
というか他のcreateは大丈夫なのかな?

**Comment by Takeno-hito** [comment]
実装を変えるのそこまで手間じゃないかなぁ…とか思ってたりする。default文無視して毎回waiting指定しとけばいいし
createはrevisionだけなので大丈夫(articleはupdateだし)

**Comment by ibuki2003** [comment]
あの、作ったあとにfindして返す発想はだめです?

**Comment by Takeno-hito** [comment]
そっちの方がコード汚くなりそうじゃない?

**Comment by ibuki2003** [comment]
じゃあmodel側でデフォ値を指定するべきでしょ

**Comment by Takeno-hito** [comment]
え、できるの?完全に調べてないですごめんなさい

**Comment by ibuki2003** [comment]
backで変える流れになったのでbackにissueを立てます

**Comment by ibuki2003** [comment]
このissueに存在価値はなくなったのでclose
