### ISSUE TITLE
OGImageで自由に改行できるようにしたい

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#61]
- [x] discuss
- [x] back
- [ ] front

改行ルールを定めてswaggerに乗っけて作業という流れになると思います

**Comment by Takeno-hito** [comment]
%0a (asciiの改行文字)を改行文字に使う。現状のバグを治すついで
でいい?

**Comment by Takeno-hito** [comment]
タイトルに改行文字を入れる事で決定。back、frontともに修正が必要で、swaggerは特にいじらなくていいかな
back→改行したときに文字が重なる → afes-website/back#73
front→タイトルが改行しちゃう

**Comment by su8ru** [comment]
タイトルの改行コード消し、backでやりたい
frontだと変えるところが多すぎて…

**Comment by Takeno-hito** [comment]
閉じてください
