### ISSUE TITLE
(特に寄稿で)執筆者の名前を設定できるようにする

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#62]
- [x] discuss
- [x] swagger
- [x] back
- [x] front

とりあえずbackの実装方針はまた考えるとして、swaggerを考えないといけない

**Comment by Takeno-hito** [comment]
検索の条件をどうするか決めたい、backに検索はすでにあるから

**Comment by Takeno-hito** [comment]
とじちゃった

**Comment by su8ru** [comment]
🎉
