### ISSUE TITLE
タイトルに絵文字が含まれる場合に崩壊する

### ISSUE THREAD

**Issue by su8ru** [afes-website/docs#67]
`なあ同輩😥`:
![image](https://user-images.githubusercontent.com/33474143/85246296-39b47800-b485-11ea-8a20-c24c9e31d95a.png)

### 選択肢は2つ
- タイトルには絵文字使用禁止
- Back-end でどうにかする？

**Comment by Takeno-hito** [comment]
正直あってもなくてもいい、backが面倒ならなしにしようぜ、というくらい

**Comment by Takeno-hito** [comment]
#61 と合わせて特殊文字場合分けをして対応した方がいいかも?

**Comment by su8ru** [comment]
タイトルは絵文字禁止にしたいなぁ…

- GD でフォールバックフォントが指定できなさそうなので、Unicodeで範囲指定して置換とかめんどうなことをやらないといけない
- frontで絵文字パーサーを通さないといけない場所が増える（Twemojiの場合）

**Comment by Takeno-hito** [comment]
タイトルの絵文字は禁止にして寄稿ルールに掲載する方針で。close
