### ISSUE TITLE
ogimage preview に + が入ると死ぬ

### ISSUE THREAD

**Issue by su8ru** [afes-website/docs#73]
query で渡しているので、`+` が ` ` になっちゃう

影響範囲は preview だけなのでそこまで重大な問題でもないけど一応

**Comment by ibuki2003** [comment]
これ、PHPの問題ぽい 昔試行錯誤して諦めた経緯があります

**Comment by su8ru** [comment]
query で渡してる限りは避けられないだろうなぁ…

**Comment by su8ru** [comment]
特殊文字が入る可能性のあるものを query で渡すのは避けたほうがいいのかもね
ところでエンコードするんじゃだめだったのか…？
