### ISSUE TITLE
フォントアイコンの選定

### ISSUE THREAD

**Issue by ibuki2003** [afes-website/docs#8]
アイコンセットどうしますか
GitHubかFontAwesomeかGoogleか、くらい
ほかにもあるのでひととおり確認する方がよさそう

もしくは 使わない選択肢もある

**Comment by su8ru** [comment]
Octicons はJSかRailsを使う必要があるっぽいですね、めんどくさそう（あんま見てない）

Font Awesome はclassなので補完が効いて楽
ただ最近有料プランとかが面倒なので悩みどころ

Google使ったことないけどこんな感じらしい
Font Awesome の有料プランの面倒さと天秤
```html
<i class="material-icons">
view_list
</i>
```

**Comment by ibuki2003** [comment]
- Octicons JS使う必要が…→このプロジェクトはVueを使用しているのでパッケージ落としてくれば1行ですよ
- Google テキストでもいいとおもうし(上記同様)npmパッケージは見当たらないけど簡単に作れそうだし補完はいくらでも効かせられる

**Comment by ibuki2003** [comment]
いくつか候補出して選んでもらうのがいいのかな

**Comment by su8ru** [comment]
Octicons は数にちょっと不安があるか…？
そんなにたくさん使うわけではないが選択肢は多いほうがいい

記述を端的に済ませられるのは Font Awesome なんだよな…
アイコンフォントの覇権を握ってそうなだけある

候補出したところで違いはそんなに無いからな…
まあ決めるには手っ取り早いが

**Comment by ibuki2003** [comment]
FontAwesomeにするということでよい?
