### ISSUE TITLE
文化祭管理の実装をする

### ISSUE THREAD

**Issue by Takeno-hito** [afes-website/docs#81]
- [x] docs
- [x] back
- [x] app

Term の条件: #196

**Comment by su8ru** [comment]
## リストバンドの仕様

### XX- (prefix)

`${種別}${色}`-

#### 種別

- `G` : Guest
- `S` : Student
- `T` : Test

#### 色

##### Guest

`B`, `R`, `Y`, `V`, `O`, `G`, `W` (予備)

##### Student

`G` Gray

##### Test

`B`, `R`, `Y`

### XXXXX

事前にランダム生成

生徒については、学年組番号で表し、2日間共通とする
例: `H2246` `M1647`
→ SG については、同一 id を印字したリストバンドが 2 つ存在することになる

**Comment by Takeno-hito** [comment]
Guest ID regex: `/^[A-Z]{2,3}-[2-8ac-kmnpr-z]{5}$/` ( `1l`, `9q`, `0o` を弾いたもの)

**Comment by su8ru** [comment]
- `R-0000000000`
  長い 目で追うのが辛い
- `R-00000`
  ゲスト ID と間違えそう
- `R-00000-00000`
  めっちゃ長い
- `R-0000-0000`
  目に優しい 1ブロック4文字なのが紛らわしい？
- `R-000-000`
  ゲスト ID との長さ差別化が機能していない
